[[redirects]]
  from = "/login"
  to = "/login"
  status = 301

[[redirects]]
  from = "/signup"
  to = "/signup"
  status = 301

[[redirects]]
  from = "/dashboard"
  to = "/dashboard"
  status = 301